# Generated by Django 4.2.25 on 2025-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="days_remaining",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Nombre de jours avant expiration (calculé automatiquement)",
                null=True,
                verbose_name="Jours restants",
            ),
        ),
    ]
