# Generated by Django 4.2.25 on 2025-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_certificate_days_remaining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="valid_from",
            field=models.DateField(blank=True, null=True, verbose_name="Valide depuis"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="valid_until",
            field=models.DateField(
                help_text="Date d'expiration du certificat",
                verbose_name="Date d'expiration",
            ),
        ),
    ]
