# Generated by Django 4.2.25 on 2025-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_convert_datetime_to_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Certificat archivé (ancienne version remplacée)",
                verbose_name="Archivé",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'archivage"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="archived_reason",
            field=models.CharField(
                blank=True,
                help_text="Ex: Remplacé par un certificat plus récent",
                max_length=255,
                null=True,
                verbose_name="Raison de l'archivage",
            ),
        ),
    ]
