# Generated by Django 4.2.24 on 2025-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsettings",
            name="smtp_host",
            field=models.CharField(
                default="smtp.gmail.com",
                help_text="Ex: smtp.gmail.com, smtp.office365.com",
                max_length=255,
                verbose_name="Serveur SMTP",
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                help_text="Mot de passe ou mot de passe d'application (Gmail)",
                max_length=255,
                verbose_name="Mot de passe SMTP",
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="smtp_port",
            field=models.IntegerField(
                default=587,
                help_text="587 (TLS) ou 465 (SSL) ou 25 (non sécurisé)",
                verbose_name="Port SMTP",
            ),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="smtp_timeout",
            field=models.IntegerField(default=10, verbose_name="Timeout (secondes)"),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="smtp_use_ssl",
            field=models.BooleanField(default=False, verbose_name="Utiliser SSL"),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True, verbose_name="Utiliser TLS"),
        ),
        migrations.AddField(
            model_name="emailsettings",
            name="smtp_username",
            field=models.CharField(
                blank=True,
                help_text="Adresse email complète",
                max_length=255,
                verbose_name="Nom d'utilisateur SMTP",
            ),
        ),
    ]
