# Generated by Django 4.2.25 on 2025-10-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_emailsettings_smtp_host_emailsettings_smtp_password_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrule",
            name="celery_task_name",
            field=models.CharField(
                blank=True,
                help_text="Ex: notifications.tasks.send_rule_alert",
                max_length=255,
                null=True,
                verbose_name="Nom de la tâche Celery",
            ),
        ),
        migrations.AddField(
            model_name="notificationrule",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manuel (via interface)"),
                    ("automatic", "Automatique (Celery Beat)"),
                ],
                default="manual",
                max_length=10,
                verbose_name="Type de planification",
            ),
        ),
    ]
